# Generated by Django 4.2.23 on 2025-07-23 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=10)),
                ('feedback', models.TextField()),
                ('sentiment', models.CharField(max_length=20)),
                ('datetime_given', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usermodel')),
            ],
            options={
                'db_table': 'user_feedback',
            },
        ),
    ]
