# Generated by Django 4.2.23 on 2025-07-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_feedbackmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackModel',
        ),
    ]
