# Generated by Django 4.2.23 on 2025-07-23 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0003_delete_feedbackmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionModel',
            fields=[
                ('interac_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500, null=True)),
                ('interac_type', models.CharField(max_length=50, null=True)),
                ('datetime_sent', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='mainapp.usermodel')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='mainapp.usermodel')),
            ],
            options={
                'db_table': 'interactions_details',
            },
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=500, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('sentiment', models.CharField(max_length=50, null=True)),
                ('datetime_reviewed', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='mainapp.usermodel')),
            ],
            options={
                'db_table': 'user_feedbacks',
            },
        ),
    ]
